# Configure drush site aliases, "local" is mandatory and used to project-make & project-install (contains all settings)
aliases:
    local:
        # Put here the path to project.make or leave empty to use default Drupal's distribution
        makefile: etc/project.make
        uri: http://drupal.local.website:8080
        root: /absolute/path/to/drupal/docroot
        remote-host: localhost
        remote-user: account

        # Database connection options
        db:
            host: localhost
            username : root
            password : root
            port: 3306
            database : skeledrup
            root_username: root
            root_password: root

        # Create these users during installation
        users:
            # override: true # if TRUE in local.yml will override values defined here
            admin: # admin is mandatory, DO NOT DELETE!
                name: admin # Customise "admin" username - defaults to admin
                pass: password
                mail: cristian.romanescu@eaudeweb.ro
        variables:
            # override              : true # if TRUE in local.yml will override values defined here
            # Mandatory variables
            site_mail               : cristian.romanescu@eaudeweb.ro
            site_name               : trakker
            site_frontpage          : node
            file_public_path        : sites/default/files
            file_default_scheme     : public
            user_register           : 0 # 0-USER_REGISTER_ADMINISTRATORS_ONLY/1-USER_REGISTER_VISITORS/2-USER_REGISTER_VISITORS_ADMINISTRATIVE_APPROVAL
            site_default_country    : RO
            date_default_timezone   : UTC+2
            admin_theme             : seven
            # Optional variables
            site_slogan             : Default site slogan
            default_nodes_main      : 10
            site_403                :
            site_404                :
            # File related settings
            file_private_path       :
            file_temporary_path     :
            user_cancel_method      :
            user_pictures           : 0
            theme_default           : bartik
            date_first_day          : 1
            configurable_timezones  : 0
            user_default_timezone   : 0
            jquery_update_compression_type      : min
            jquery_update_jquery_admin_version  :
            jquery_update_jquery_cdn            : none
            jquery_update_jquery_version        : 1.9

        devify:
            disable-modules: [update]
            enable-modules:  [devel]
            delete-variables: []
            reset-variables: []

    dev:
        uri: http://php-support.edw.ro:8080
        root: /var/www/html/php-support.edw.ro
        remote-host: php-devel1.edw.lan
        remote-user: php
